services:
  - type: web
    name: masbaratodeals-final
    env: node
    plan: free
    buildCommand: ./render-build.sh
    startCommand: node index.js
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_VERSION
        value: 20.x
      - key: AMAZON_TAG
        value: masbaratodeal-20
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHANNEL_ID
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: FACEBOOK_ACCESS_TOKEN
        sync: false
      - key: FACEBOOK_PAGE_ID
        sync: false
      - key: INSTAGRAM_USER_ID
        sync: false
