services:
  - type: web
    name: masbaratodeals-final
    env: node
    plan: free
    buildCommand: ./render-build.sh
    startCommand: node index.js
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_VERSION
        value: 20.x
      - key: AMAZON_TAG
        value: masbaratodeal-20
